### ISSUE TITLE
Agregar correo electronico a Mardown "group_3_ass_1_2024_task1"

### ISSUE THREAD

**Issue by FernandoTem** [alexanderquispe/QLAB_Summer_Python#146]
Hola @Luci8as, 

Debido a que completaste el texto del archivo tarea 1, ahora te solicito agregar tu correo electrónico al costado de tu nombre en el mismo archivo, de esta forma:
2. Lucia (correo electrónico)

gracias.

**Comment by Luci8as** [comment]
Genial, ahora lo añado. 

Gracias.
